FROM node:20-bullseye

WORKDIR /app

RUN apt-get update && apt-get install -y adb git && rm -rf /var/lib/apt/lists/*

COPY package*.json ./

EXPOSE 19000 19001 19002 8081 19006

CMD ["sh", "-c", "npm install && npx expo start --host 0.0.0.0 --lan --non-interactive"]
